config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :users
  resources :sessions
  resources :organizations

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	  validates :name, presence: true, length: { in: 5..200 }
	  validates :description, presence: true, length: { in: 10..200 }
end

app/models/user.rb
class User < ActiveRecord::Base
		EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, :password, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	def create
		@member = Member.new
		@person = User.find(session[:user_id])
		@organizer_name = @person.first_name + @person.last_name
		@org = Organization.create(name:params[:organization][:name], description:params[:organization][:description], user:@organizer_name)
		if @org.valid?
			
			Member.create(organization_id:@org.id, first_name:@person.first_name, last_name:@person.last_name)
			redirect_to new_session_path
		else 
			flash[:error] = @org.errors.full_messages
			redirect_to new_session_path
		end
	end

	def show
		@members = Member.all
		@person = User.find(session[:user_id])
		@org = Organization.find(params[:id])
		@is_member = Member.find_by_organization_id_and_first_name_and_last_name(params[:id], @person.first_name, @person.last_name)
	end

	def update
		@person = User.find(session[:user_id])
		Member.create(organization_id:params[:id], first_name:@person.first_name, last_name:@person.last_name)
		redirect_to :back
	end

	def destroy
		@person = User.find(session[:user_id])
		Member.find_by_organization_id_and_first_name_and_last_name(params[:id], @person.first_name, @person.last_name).destroy
		redirect_to :back
	end



	def index
		@user = User.find session[:user_id]
		@organizations = Organization.all
		@org = Organization.new
		@members = Member.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@members = Member.all
		@organization = Organization.new
		@organizations = Organization.all
		@user = User.find_by(user_params)
		if @user.password == params[:user][:password]
			session[:user_id] = @user.id
		else
			flash[:error] = "Invalid email or password"
			redirect_to root_path
		end		
	end 

	def new
		@organization = Organization.new
		@organizations = Organization.all
		@members = Member.all
		@user =  User.find session[:user_id]
	end

	def index
		@members = Member.all
		@organization = Organization.new
		@user = User.find session[:user_id]
		@organizations = Organization.all
		
	end

	def user_params
		params.require(:user).permit(:email)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.new
	end

	def create
		@user = User.create( user_params)
		if @user.valid?
			flash[:success] = "Successfully registered, please log in"
			redirect_to root_path
		else
			flash[:error] = @user.errors.full_messages
			redirect_to root_path
		end
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBelt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organizations/show.html.erb
<%= link_to "DashBoard", new_session_path %>
<%= link_to "Logout", root_path %>
<p>Name Of Event</p>
<p><%= @org.name%></p>
<p>Description</p>
<p><%= @org.description%></p>
<p>Event Planner</p>
<p><%= @org.user%></p>

<% if @is_member%>
<%= form_for @org , method: :delete do |f| %>
  <%= f.submit "Leave Event"%>
  <% end %>

 <%else%>
 <%= form_for @org do |f| %>
  <%= f.submit "Join Event" %>
<%end%>
<% end %>


<p>Memebers:</p>
<% @members.each do |member|%>
	<%if member.organization_id == @org.id%>
	<p><%= member.first_name%> <%= member.last_name%></p>
	<%end%>
<%end%>

app/views/users/index.html.erb
<h1>Welcome</h1>

<h3>Register Here</h3>


<%= form_for @user do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br />

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br />

  <%= f.label :email %>:
  <%= f.email_field :email %><br />

  <%= f.label :password %>:
  <%= f.password_field :password %><br />


  <%= f.submit %>
<% end %>


<%= form_for @user, :url => sessions_path do |f| %>
  <%= f.label :email %>:
  <%= f.email_field :email %><br />

  <%= f.label :password %>:
  <%= f.password_field :password %><br />

  <%= f.submit %>
<% end %>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>